name: Release FRKN Bot Hehe

on:
  push:
    tags: ["*"]

jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Prepare Artifact
        run: |
          tar -czf frkn-bot.tar.gz dist/ package.json package-lock.json

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-dist
          path: frkn-bot.tar.gz

  release:
    name: Create GitHub Release
    needs: [build-bot]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Важно для создания релиза
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: bot-dist

      - name: Release GitHub tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            frkn-bot.tar.gz
            README.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
